### PR TITLE
IA-2876 use blessed image

### PR DESCRIPTION
**Pull request by Qi77Qi**
https://broadworkbench.atlassian.net/browse/IA-2876

### CODE REVIEW

**Comment by rtitle** [comment]
🎉 

Wondering if we need `debian`? I think Leo needed it for `helm` stuff but wondering if welder could use `alpine` or even `distroless`: https://console.cloud.google.com/gcr/images/broad-dsp-gcr-public/us/base/jre?project=broad-dsp-gcr-public

**Comment by Qi77Qi** [comment]
oh good point..let me try the other two

**Comment by Qi77Qi** [comment]
@rtitle tried both distroless and alpine...both failed because either `bash` doesn't exist or `/bin/sh` doesn't exist...so I'm going to keep it as `debian` for now...the it's abt 30mg size difference between `debian` and `alpine`

**Review by kyuksel — APPROVED** [review]

**Comment by rtitle** [comment]
Ah ok 👍

**Review by rtitle — APPROVED** [review]

**Pull request merged**
